
# Notification daemon
exec-once = swaync

# Authentication agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Status bar
exec-once = waybar --config ~/.config/waybar/config.json

# Keyring
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets

# Wallpaper manager
exec-once = swww-daemon
exec-once = swww img --transition-type grow --transition-pos 0.5,1.0 .config/hypr/wallpaper/stripped.png --transition-fps 60 --transition-duration 2


# Night light if you want it...
exec-once = hyprsunset --gamma 80 --temperature 4000

# Idle timer .. locks your screen when idle
exec-once = hypridle

# Network Manager and Bluetooth Manager Applet
exec-once = nm-applet
# exec-once = blueman-applet

#forces dark theme on apps
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Dark'   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Launches your plugins
exec-once=/usr/bin/hyprpm reload -n

# Set Cursor theme 
exec-once=/usr/bin/hyprctl setcursor 'Capitaine Cursors (Gruvbox) - White' 24
